apiVersion: v1
kind: Service
metadata:
  name: chat-server
  namespace: queue-system
spec:
  type: ClusterIP
  selector:
    app: chat-server
  ports:
    - name: websocket
      port: 9000 # 클러스터/Ingress에서 보는 포트
      targetPort: 8080 # 컨테이너 실제 포트
