apiVersion: v1
kind: Service
metadata:
  name: gameserver
  namespace: queue-system
spec:
  type: ClusterIP
  selector:
    app: gameserver
  ports:
    - name: websocket
      port: 9000 # 클러스터 내부에서 gameserver 서비스가 노출되는 포트
      targetPort: 9000 # Pod 안의 containerPort
