apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: queue-ingress
  namespace: queue-system
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/group.name: queue-system
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=1200 #20분 유지

spec:
  rules:
    - http: # ← 반드시 리스트 형태여야 함!
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: queue-api
                port:
                  number: 8080

          - path: /ws # 실제 WebSocket 접속 URL 확인 필요
            pathType: Prefix
            backend:
              service:
                name: gameserver
                port:
                  number: 9000
