apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-manager
  namespace: queue-system
  labels:
    app: queue-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue-manager
  template:
    metadata:
      labels:
        app: queue-manager
    spec:
      containers:
        - name: queue-manager
          image: 061039804626.dkr.ecr.ap-northeast-2.amazonaws.com/queue-manager:latest
          imagePullPolicy: Always

          env:
            - name: SPRING_DATA_REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: valkey-secret
                  key: SPRING_DATA_REDIS_HOST

            - name: SPRING_DATA_REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: valkey-secret
                  key: SPRING_DATA_REDIS_PORT

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
