apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-api
  namespace: queue-system
  labels:
    app: queue-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: queue-api
  template:
    metadata:
      labels:
        app: queue-api
    spec:
      containers:
        - name: queue-api
          image: 061039804626.dkr.ecr.ap-northeast-2.amazonaws.com/queue-api:latest
          imagePullPolicy: Always

          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://adot-collector.observability.svc.cluster.local:4318/v1/metrics"
            - name: SPRING_DATA_REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: valkey-secret
                  key: SPRING_DATA_REDIS_HOST

            - name: SPRING_DATA_REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: valkey-secret
                  key: SPRING_DATA_REDIS_PORT

          ports:
            - containerPort: 8080

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30 # 컨테이너 뜨고 30초 뒤부터 체크 시작
            periodSeconds: 10 # 10초마다 체크
            timeoutSeconds: 3 # 3초 안에 응답 없으면 실패
            failureThreshold: 5 # 5번 연속 실패해야 진짜 실패로 간주

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60 # 완전히 자리잡고 60초 후부터 체크
            periodSeconds: 20 # 20초마다 체크
            timeoutSeconds: 3
            failureThreshold: 5
