apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: queue-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: queue-api
  minReplicas: 1
  maxReplicas: 5
